### ISSUE TITLE
Use tempfile module to determine temporary files directory in cross-platform way

### ISSUE THREAD

**Issue by markborkum** [pacifica/pacifica-cartd#19]
### Pacifica Data Cart version
1.0

### Pacifica Core Software versions
n/a

### Platform Details
All supported platforms.

### Scenario:
Trying to run the test suite on non-Unix platform.

Codebase should use `tempfile.gettempdir()` function to determine the location of the temporary files directory in a cross-platform way (c.f., https://docs.python.org/2/library/tempfile.html). 

An example affected source file is `cart/cart_env_globals.py`, where the `VOLUME_PATH` variable is [hard-coded](https://github.com/pacifica/pacifica-cartd/blob/3d94c7335461977ae50c60bee239b31d61db87d2/cart/cart_env_globals.py#L11) to `/tmp/`.

### Steps to Reproduce:
n/a

### Expected Result:
n/a

### Actual Result:
n/a

**Comment by dmlb2000** [comment]
The volume path should always be set by the deployment team of the system. This one I've flip flopped on a couple of times. Many of the interfaces we require to be compatible with (i.e. WSGI) don't lend themselves to standard configuration file management with the application. So using environment variables to transfer global state of configuration does work nicely, though not ideal. Passing configuration arguments on the command line and requiring arguments only work when running in CherryPy and not when embedded in a WSGI server. Using `argparse` or `configparser` means you read and parse the configuration for every request, without doing interesting things with globals.

So maybe the more correct solution is to check the environment variable and throw an error if it's not set. I'd be hesitant to use `tempfile` here as deployment teams would think they can just set `TMPDIR` in the environment and it will get moved. However, this could change behavior for the application in other ways when doing that.

**Comment by dmlb2000** [comment]
The point here is that `VOLUME_PATH` is a configuration that needs to be set and by default it's `/tmp` to be something but it's not a space for temporary files.
