### ISSUE TITLE
python/cart directory may be misnamed?

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-cartd#41]
### Pacifica Data Cart version
e5ff7ee8c6f2126659cf898b1c2db4405df68440

### Expected Result:
users might expect the `pacifica/cart` directory to be named `pacifica/cartd`

**Comment by GitBytes** [comment]
This also make it painful to standardize on a variable name when trying to use configuration management, like say the base of the package which is pacifica-cartd (i.e. cartd) then to have to handle the dropping of the "d" to setup celery as just "cart"

**Comment by dmlb2000** [comment]
Specifically the python module for this service is called `cart` where the repository and the python package are `cartd`.

We should pick one and stick to it!
