### ISSUE TITLE
ORM Database creation script not autogenerating tables in postgresql

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-cartd#46]
### Pacifica Cartd version
latest

### Scenario:
trying to autogenerate database schema via ORM python tooling provided

### Steps to Reproduce:
install pacifica-cartd with pip
Setup env and configs
attempt to start service script which includes:
`python -c 'from pacifica.cartd.orm import create_tables; create_tables()'`

### Expected Result:
if database is blank, create tables as necessary
if database exists, update tables to reflect current schema or close to this result

### Actual Result:
no tables are created

**Comment by GitBytes** [comment]
Found log output with some Traceback information:
```
Nov 27 14:39:16 core pacifica-cartd-frontend[11447]: """)
Nov 27 14:39:16 core pacifica-cartd-frontend[11447]: Traceback (most recent call last):
Nov 27 14:39:16 core pacifica-cartd-frontend[11447]: File "<string>", line 1, in <module>
Nov 27 14:39:16 core pacifica-cartd-frontend[11447]: ImportError: cannot import name create_tables
```

**Comment by dmlb2000** [comment]
The correct command to use now is `pacifica-cartd-cmd dbsync`... I'll update the documentation and then close this issue.
