### ISSUE TITLE
Attempted relative import in non-package

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-cartd#47]
### Pacifica Data Cart version
latest

### Scenario:
Start cartd frontend uwsgi service via pypi package

### Steps to Reproduce:
Install Pypi package for pacifica-cartd
Setup environment for cartd frontend
invoke service script that includes the wsgi.py

### Expected Result:
Starts service without error

### Actual Result:
```
Nov 27 14:39:17 core uwsgi[11447]: Traceback (most recent call last):
Nov 27 14:39:17 core uwsgi[11447]:   File "/opt/virtualenv/lib/python2.7/site-packages/pacifica/cartd/wsgi.py", line 6, in <module>
Nov 27 14:39:17 core uwsgi[11447]:
Nov 27 14:39:17 core uwsgi[11447]: from .rest import CartRoot, error_page_default
Nov 27 14:39:17 core uwsgi[11447]: ValueError
Nov 27 14:39:17 core uwsgi[11447]: :
Nov 27 14:39:17 core uwsgi[11447]: Attempted relative import in non-package
Nov 27 14:39:17 core uwsgi[11447]:
Nov 27 14:39:17 core uwsgi[11447]: unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by dmlb2000** [comment]
You might try using the `--module` command line argument for uwsgi.

`--module 'pacifica.cartd.wsgi:application'`
