### ISSUE TITLE
Cart should call stage_files with delay

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-cartd#6]
### Pacifica Data Cart version
Master

### Pacifica Core Software versions
Master

### Platform Details
Any

### Scenario:
When creating large carts with thousands of files the call to `stage_files` takes a long time and a client might timeout. We should call `stage_files` with the `delay()` method to return more quickly.

### Steps to Reproduce:
Create a cart with 1000 files.

### Expected Result:
Return in seconds

### Actual Result:
Returns in 10s of seconds

**Comment by dmlb2000** [comment]
@ChristopherKnight Could you make this a priority to fix?

**Comment by ChristopherKnight** [comment]
Beginning work on this now
