### ISSUE TITLE
[Bug] Cleanup deleted cart symlinks when cart is deleted

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-cartd#65]
### Pacifica Data Cart version
v0.3.9

### Scenario:
Deleting a cart with `export BUNDLE_TASK=on` the cart bundle itself is deleted but the symlink remains and is now a broken link. When the cart is deleted, the symlink should be removed as well.

### Steps to Reproduce:
Enable BUNDLE_TASK in some way in the cartd config, create cart, delete cart.

### Expected Result:
Symlink should be gone, cart should be gone.

### Actual Result:
Cart is deleted, and symlink remains.

**Comment by GitBytes** [comment]
Woot, thanks @dmlb2000 !

**Comment by dmlb2000** [comment]
This still wasn't fixed...

**Comment by dmlb2000** [comment]
I can't reproduce the bug on my end, carts are deleting the `cartuids` symlinks... We really need to drop python 2 support and then we can support his better with coverage and assertions in our unit tests...
