### ISSUE TITLE
fixit functionality does not only fix errors.

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-cartd#99]
### Pacifica Data Cart version
0.6.0

### Platform Details
Centos7

### Scenario:
A large download ~30 large tar files are in a cart.  one file fails a hash check for some reason:

`bin/pacifica-cartd-cmd fixit --cartid 65349451ffaa102f710ad215bbe0f5954efbe4fb9c42c8f37d34af29291b5e2e
`
### Steps to Reproduce:
run the command.
### Expected Result:
one file to be downloaded and staged, then the cart completed.

### Actual Result:
All the files are download serially....

**Comment by dmlb2000** [comment]
It would be good to include support for the byte range options. However, we should first, verify completeness in the API by [testing aria2](https://github.com/pacifica/pacifica-archiveinterface/issues/107) directly against the archive interface.

**Comment by karcaw** [comment]
this isnt really about aria2. this is about fixing a single file in a failed cart.  the fixit tool tries to fix ALL the files, not just the one that failed.
